-- -----------------------QUERIES-------------------------------------
-- -------------------------------------------------------------------
-- -------------------------------------------------------------------
-- -------------------------------------------------------------------

-- How many distinct product lines are there in the dataset?

select count(distinct product_id) from products_dataset;

-- What is the most selling product line?

select product_id, sum(quantity)
from purchase_history_dataset
group by product_id
order by sum(quantity) desc
limit 1;

-- What is the total revenue by month?

select month(purchase_date) as month, truncate(sum(total_amount),2) as Revenue
from  purchase_history_dataset
group by  month
order by month;

-- Which city has the highest revenue?

select city, sum(quantity) as Total_orders, sum(total_amount) as revenue 
from customer_profile_dataset
inner join purchase_history_dataset
on purchase_history_dataset.customer_id=customer_profile_dataset.customer_id
group by customer_profile_dataset.city
order by revenue desc 
limit 1;


-- Which brand sold more products than average product sold?			

select brand, sum(quantity) as Total_Quantity
from products_dataset 
join purchase_history_dataset
on products_dataset.product_id = purchase_history_dataset.product_id
group by brand
having sum(quantity)>(select sum(quantity)/(select count(distinct brand) from products_dataset) 
from purchase_history_dataset 
cross join products_dataset 
on purchase_history_dataset.product_id=products_dataset.product_id);


-- What is the most common product by gender?

(SELECT gender, product_id, Count(gender) AS total_cnt
FROM purchase_history_dataset right join customer_profile_dataset
on purchase_history_dataset.customer_id=customer_profile_dataset.customer_id
where gender="Female"
group by product_id
order by total_cnt desc
limit 1)
union
(SELECT gender, product_id, COUNT(gender) AS total
FROM purchase_history_dataset right join customer_profile_dataset
on purchase_history_dataset.customer_id=customer_profile_dataset.customer_id
where gender="Male"
GROUP BY product_id
order by total desc 
limit 1);


-- What was the yearwise total for sales?

select year(purchase_date) as Year, truncate(sum(total_amount),2) as Revenue
from  purchase_history_dataset
group by  Year
order by Revenue desc;

-- What was the best month for sales?

select month(purchase_date) as month, truncate(sum(total_amount),2) as Revenue
from  purchase_history_dataset
group by  month
order by Revenue desc
limit 1;

/* What was the total revenue generated by the retailer during the time
period covered by the dataset?*/

select truncate(sum(total_amount),2) as Total_Revenue
from purchase_history_dataset;

-- Which product had the highest total revenue?

select brand, products_dataset.product_id, truncate(sum(total_amount),2) as product_Revenue
from purchase_history_dataset left join products_dataset
on purchase_history_dataset.product_id=products_dataset.product_id
group by brand, products_dataset.product_id
order by product_revenue desc
limit 1;

-- Who are the Top 5 customers that generated the most revenue for the retailer?

select customer_profile_dataset.customer_id, concat(first_name, last_name)as name,
truncate(sum(total_amount),2) as Revenue 
from customer_profile_dataset left join purchase_history_dataset
on customer_profile_dataset.customer_id=purchase_history_dataset.customer_id
group by customer_profile_dataset.customer_id, name
order by Revenue desc 
limit 5;